#Deny incomming traffic by default
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: helpet-app
  name: default-deny-ingress
spec:
  podSelector: {}
  policyTypes:
    - Ingress

---

#Allow incoming traffic to the frontend from the ingress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-ingress
  namespace: helpet-app
spec:
  podSelector:
    matchLabels:
      run: helpet-frontend
  ingress:
  - from:
      - namespaceSelector:
          matchLabels:
            name: ingress-basic
    ports:
      - port: 3000
        protocol: TCP
  policyTypes:
    - Ingress

---

#Allow incoming traffic to backend from the ingress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-ingress
  namespace: helpet-app
spec:
  podSelector:
    matchLabels:
      run: helpet-backend
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-basic
      ports:
      - port: 3001
        protocol: TCP
  policyTypes:
    - Ingress
